<a href="https://colab.research.google.com/github/Ayesha-Zaman/Intelligence-Journey-/blob/main/07%3A%20Advanced%20Pandas/%20GroupBy%20Object%20in%20Pandas/%20Task%2019%3A%20GroupBy%20Object%20in%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [1]:
import pandas as pd
import numpy as np

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

In [2]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [3]:
# code

pclass_group = titanic_df.groupby('Pclass')
for group,data in pclass_group:
  print(f'Pclass {group}: Avg Age {data['Age'].mean()}, Missing values {data['Age'].isna().sum()}')

Pclass 1: Avg Age 38.233440860215055, Missing values 30
Pclass 2: Avg Age 29.87763005780347, Missing values 11
Pclass 3: Avg Age 25.14061971830986, Missing values 136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [4]:
pclass_group = titanic_df.groupby('Pclass')
for group,data in pclass_group:
  print(data['Embarked'].fillna(data['Embarked'].mode()).value_counts(ascending = True))

Embarked
Q      2
C     85
S    127
Name: count, dtype: int64
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [5]:
# code
my_dict = {}

embarked_groups = titanic_df.groupby('Embarked')

for emb_group,emb_data in embarked_groups:
  pclass_groups = emb_data.groupby('Pclass')
  my_dict[emb_group] = {}
  for p_group,p_data in pclass_groups:
    my_dict[emb_group][p_group] = round(p_data['Fare'].mean(), 2)

my_dict

{'C': {1: np.float64(104.72), 2: np.float64(25.36), 3: np.float64(11.21)},
 'Q': {1: np.float64(90.0), 2: np.float64(12.35), 3: np.float64(11.18)},
 'S': {1: np.float64(70.36), 2: np.float64(20.33), 3: np.float64(14.64)}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [6]:
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df.head(2)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [7]:
# code
def z_normalization(group, cols_to_perform):
  for col in cols_to_perform:
    group[f'{col}_z_norm'] = (group[col] - group[col].mean()) / (group[col].std())
  return group

groups = fifa_df.groupby('Team', group_keys=False)
cols_to_perform = ['Passes','Passes Completed','Attempted Line Breaks','Completed Line Breaks']
groups = groups.apply(z_normalization, cols_to_perform = cols_to_perform).groupby("Team")
groups.agg(
    {
        'Passes':['min','max'],
        'Yellow Cards':['min','max', 'mean'],
        'Attempted Line Breaks':['min','max', 'std'],
        'Possession (%)':['mean']
    }
)

/tmp/ipython-input-2223661556.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  groups = groups.apply(z_normalization, cols_to_perform = cols_to_perform).groupby("Team")

               Passes       Yellow Cards               Attempted Line Breaks  \
                  min   max          min max      mean                   min
Team
Argentina         408   862            0   8  2.285714                   141
Australia         286   466            0   3  1.750000                   133
Belgium           512   685            1   3  1.666667                   167
Brazil            548   695            0   3  1.200000                   164
Cameroon          295   500            1   5  2.666667                   144
Canada            448   536            2   4  2.666667                   102
Costa Rica        231   454            1   3  2.000000                    86
Croatia           461   724            0   2  1.142857                    97
Denmark           537   650            1   2  1.666667                   173
Ecuador           429   484            0   2  1.000000                   143
England           508   810            0   1  0.200000                   133
France            358   734            0   3  1.142857                   126
Germany           352   827            0   3  1.000000                   143
Ghana             319   460            2   4  2.666667                   122
Iran              232   463            2   3  2.333333                    56
Japan             225   591            0   3  1.500000                   104
Korea Republic    359   548            1   2  1.500000                   139
Mexico            356   500            1   4  2.333333                   127
Morocco           229   583            0   3  1.285714                   128
Netherlands       403   786            0   4  1.800000                   168
Poland            303   466            1   3  1.750000                    79
Portugal          461   678            0   3  1.200000                   165
Qatar             424   457            0   4  2.333333                   159
Saudi Arabia      267   560            2   6  4.666667                   147
Senegal           277   511            1   3  1.750000                   143
Serbia            403   513            2   7  4.000000                   140
Spain             647  1070            0   1  0.500000                   186
Switzerland       403   512            1   4  2.250000                   157
Tunisia           328   501            1   3  1.666667                   153
United States     427   572            0   4  1.250000                   143
Uruguay           390   528            1   3  2.000000                   146
Wales             325   508            1   2  1.666667                   104

                               Possession (%)
                max        std           mean
Team
Argentina       249  38.774685      49.285714
Australia       171  17.682383      31.250000
Belgium         195  14.422205      49.000000
Brazil          193  10.691118      50.400000
Cameroon        182  19.857828      38.333333
Canada          176  37.753587      44.333333
Costa Rica      154  38.974351      27.333333
Croatia         259  54.499891      47.428571
Denmark         241  34.000000      51.333333
Ecuador         177  17.009801      42.666667
England         208  29.676590      57.200000
France          179  21.407609      44.857143
Germany         256  56.624494      53.000000
Ghana           188  33.020196      37.000000
Iran            195  77.526340      31.666667
Japan           253  64.048810      30.250000
Korea Republic  201  27.072434      42.250000
Mexico          198  40.706265      46.666667
Morocco         157  10.641339      34.285714
Netherlands     198  12.759310      44.000000
Poland          156  36.326070      32.000000
Portugal        197  13.049904      53.800000
Qatar           174   7.767453      39.333333
Saudi Arabia    205  29.022979      36.666667
Senegal         184  16.938615      38.500000
Serbia          184  22.188586      42.666667
Spain           237  24.289916      67.000000
Switzerland     178   9.032349      43.000000
Tunisia         200  24.419937      38.666667
United States   204  27.693260      47.000000
Uruguay         186  22.030282      41.000000
Wales           208  53.028294      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning